name: Run Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install and Configure Poetry
      run: |
        pip install poetry==1.5.1
        poetry config virtualenvs.in-project true

    - name: Set up Cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: poetry install --only main

    - name: Run Pytest
      run: poetry run pytest
